version: '3.3'
services:
  db:
    image: postgres:9.6-alpine
  products-api:
    build: ./
    command: rails s -p 3000 -b 0.0.0.0
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
